# Generated by Django 2.2.1 on 2019-06-05 16:17

# -*- coding: utf-8 -*-
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('family', models.IntegerField(default=0)),
                ('education', models.IntegerField(default=0)),
                ('friendship', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('wealth', models.IntegerField(default=0)),
                ('love', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
